### ISSUE TITLE
Provide instructions for marking attendance using remote device

### ISSUE THREAD

**Issue by mayank26saxena** [Husseinfo/tracker#2]
Please provide instructions regarding marking attendance using a remote device (RPi) and a local device.

**Comment by Husseinfo** [comment]
You can use one of the scripts `realtime.py`, `tracker.py` and `rtracker.py` with slight modifications regarding the connection configuration.
You can also develop your own RESTful client to talk to the web service (see `receive_recognize ` in `views.py`).

**Comment by mayank26saxena** [comment]
Is it possible to do real-time attendance marking with the webcam (on my system) using the Django web app?

**Comment by mayank26saxena** [comment]
Is it possible to do real-time attendance marking with the webcam (on my system) using the Django web app?

**Comment by mayank26saxena** [comment]
Is it possible to do real-time attendance marking with the webcam (on my system) using the Django web app?

**Comment by Husseinfo** [comment]
The purpose of `Capture` is to test the system recognition.
The attendance is marked from outside (using the RESTful API) without the user interaction.
