### ISSUE TITLE
css and js not loading

### ISSUE THREAD

**Issue by Haroonhsa007** [Husseinfo/tracker#23]
After install then project 
login page works fine but after loging then template design was
![image](https://github.com/Husseinfo/tracker/assets/146448361/575a35a4-de5f-427d-b771-c0aa7e953783)

**Comment by Husseinfo** [comment]
upgrade to bs5

**Comment by Haroonhsa007** [comment]
> upgrade to bs5

Are you referring bs5 as BootStrap Version 5

**Comment by Husseinfo** [comment]
> > upgrade to bs5
> 
> Are you referring bs5 as BootStrap Version 5

Yes, it is now on main branch.

**Comment by Haroonhsa007** [comment]
> > > upgrade to bs5
> > 
> > 
> > Are you referring bs5 as BootStrap Version 5
> 
> Yes, it is now on main branch.

Thank You Sir, I will test and may use your code. 
😌
