### ISSUE TITLE
Unable to start the application

### ISSUE THREAD

**Issue by ayushbest** [Husseinfo/tracker#4]
Still getting the same error after trying to login.

Error -
relation "tracker_user" does not exist LINE 1: SELECT COUNT(*) AS "__count" FROM "tracker_user"

**Comment by Husseinfo** [comment]
You need to run django migration commands
```python3 manage.py makemigrations```
```python3 manage.py migrate```

**Comment by ayushbest** [comment]
Yes I know I ran the commands before hand but it doesn't seem to work it still gives the same error after the sign in page
